Added support for other devices using cp210x
tidepool-org/cp2102 pull request #12
Opened 2021-01-22 17:41 UTC by simonarnell

Per discussion in #8.

2021-01-25 10:43 UTC, gniezen requested changes
Some changes requested inline. Also, would you mind adding the new options (e.g. `transfers` and `wordLength`) to the README?

2021-01-25 10:43 UTC, gniezen commented on index.js
> +      self.emit('ready');
Now that this isn't wrapped in the `async` section anymore, doesn't that mean that it will fire before the `async` section completes?

2021-01-25 10:43 UTC, gniezen commented on index.js
> +      } else self.inEndpoint.startPoll();
Would you mind wrapping the `else` section in `{ }` for readability?

2021-08-23 14:11 UTC, gniezen commented
@simonarnell I was wondering if you still wanted to address the requested changes on this PR?

2022-09-21 10:56 UTC, gniezen commented
@krystophv Would you mind the reviewing the changes I've made to this PR?

2022-09-28 08:42 UTC, gniezen commented
@krystophv I still need a review on this PR before I can merge.

2022-09-28 14:06 UTC, krystophv approved these changes
LGTM 👍🏼

2022-09-28 14:19 UTC, gniezen approved these changes

2022-09-28 14:19 UTC, merged